# LISTING
ObCmsBundle_module_list:
    pattern: /{name}
    defaults: { _controller: ObCmsBundle:Admin:list }

ObCmsBundle_module_actions:
    pattern: /{name}/actions
    defaults: { _controller: ObCmsBundle:Admin:actions }


# CREATE
ObCmsBundle_module_new:
    pattern: /{name}/new
    defaults: { _controller: ObCmsBundle:Admin:new }

ObCmsBundle_module_create:
    pattern: /{name}/create
    defaults: { _controller: ObCmsBundle:Admin:create }
    requirements: { _method: post }


# EDIT
ObCmsBundle_module_edit:
    pattern: /{name}/{id}/edit
    defaults: { _controller: ObCmsBundle:Admin:edit }

ObCmsBundle_module_update:
    pattern:  /{name}/{id}/update
    defaults: { _controller: "ObCmsBundle:Admin:update" }
    requirements: { _method: post }


# DASHBOARD
ObCmsBundle_module_dashboard:
    pattern: /
    defaults: { _controller: ObCmsBundle:Admin:dashboard }