parameters:
    ob.cms.admin_container.class: Ob\CmsBundle\Admin\AdminContainer

services:
    ob.cms.admin_container:
        class: %ob.cms.admin_container.class%

    ob.cms.twig.extension:
        class: Ob\CmsBundle\Twig\TwigExtensions
        tags:
            - { name: twig.extension }
