parameters:
    ob.cms.admin_container.class: Ob\CmsBundle\Admin\AdminContainer

services:
    ob_cms.controller:
        class: %ob_cms.classes.controller%
        arguments:
            - @templating
            - @doctrine.orm.entity_manager
            - @form.factory
            - @router
            - @session
            - @knp_paginator
            - @ob.cms.admin_container
            - %ob_cms.templates%
        scope: request

    ob.cms.admin_container:
        class: %ob.cms.admin_container.class%

    ob.cms.twig.extension:
        class: Ob\CmsBundle\Twig\TwigExtensions
        arguments: [ %ob_cms.configs% ]
        tags:
            - { name: twig.extension }
