parameters:
    ob.cms.admin_container.class: Ob\CmsBundle\Admin\AdminContainer

services:
    ob_cms.controller:
        class: %ob_cms.classes.controller%
        arguments:
            - @templating
            - @doctrine.orm.entity_manager
            - @form.factory
            - @router
            - @session
            - @ob.cms.admin_container
            - @ob.cms.admin.datagrid
            - %ob_cms.templates%
            - @ob.cms.admin.exporter
        scope: request

    ob.cms.admin_container:
        class: %ob.cms.admin_container.class%

    ob.cms.twig.extension:
        class: Ob\CmsBundle\Twig\TwigExtensions
        arguments: [ %ob_cms.configs% ]
        tags:
            - { name: twig.extension }

    ob.cms.admin.exporter:
        class: Ob\CmsBundle\Export\Exporter
        calls:
            - [ addExporter, [ @ob.cms.admin.xls_exporter ] ]

    ob.cms.admin.xls_exporter:
        class: Ob\CmsBundle\Export\XlsExporter
        arguments: [ @phpexcel ]

    ob.cms.admin.datagrid:
        class: Ob\CmsBundle\Datagrid\Datagrid
        arguments: [ @request, @doctrine.orm.entity_manager, @knp_paginator ]
        scope: request